### ISSUE TITLE
Invalid repo name

### ISSUE THREAD

**Issue by ianrios** [KellyLWilson/KellyLWilson.github.io#21]
For the blog, you need to be working in a repo called `KellyLWilson.github.io`, not one called "my-app"; my-app is too vague. See step 2 of "Setup -> [Process](https://github.com/bootcamp-students/Resources/wiki/Basic-Blog#setup)"

**Comment by KellyLWilson** [comment]
I have the original one I setup and I have been meaning to go back and work from there, but (as you can tell) my blog is where I have been totally dropping the ball.  I will do that ASAP!
Thank you,Kelly
    On Monday, February 17, 2020, 04:58:00 PM EST, Ian Rios <notifications@github.com> wrote:  
 
 
For the blog, you need to be working in a repo called KellyLWilson.github.io, not one called "my-app"; my-app is too vague. See step 2 of "Setup -> Process"

**Comment by KellyLWilson** [comment]
I renamed my blog to KellyLWilson.github.io, updated the link, and cloned the repo to my local machine via terminal.
